name: Build Alioth Kernel (Only KSU/SUSFS)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git curl wget bison flex zip bc cpio libssl-dev ccache python-is-python3 tar

    - name: Setup zyc-clang toolchain
      run: |
        mkdir -p $HOME/zyc-clang
        cd $HOME/zyc-clang
        wget https://github.com/ZyCromerZ/Clang/releases/download/15.0.7-20251111-release/Clang-15.0.7-20251111.tar.gz
        tar -zxvf Clang-15.0.7-20251111.tar.gz
        cd $GITHUB_WORKSPACE

    # 编译 Alioth (参数 alioth 会传给 build.sh，或者脚本也会默认使用 alioth)
    - name: Build kernel for Alioth
      run: |
        bash build.sh alioth

    # 上传产物到 GitHub Actions Summary
    - name: Upload zip
      uses: actions/upload-artifact@v4
      with:
        name: Kernel_Alioth_KSU_SUSFS
        path: |
          Kernel_MIUI_alioth*.zip
